spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
###

###
#config jwt
hoidanit.jwt.base64-secret=pMPQGJtz+jfWK8668DRA6fcHiJDOGmf1Jvj4otSTytBeNoT3QdNcAQ2MY8vTYRS3hGJOn6Hjp5RYiHlf8Jd9Tw==
#expiration : 1 day (seconds = 24 * 60 * 60)
# 100 days
hoidanit.jwt.access-token-validity-in-seconds=8640000
hoidanit.jwt.refresh-token-validity-in-seconds=8640000
#
###

#config upload file
###
# #default = 1MB
spring.servlet.multipart.max-file-size=50MB

# #default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB

#base path
hoidanit.upload-file.base-uri=file:///Users/phamducthanh/Library/CloudStorage/GoogleDrive-taothichmi2009@gmail.com/My%20Drive/HoidanIT/Java_Spring_REST_Ultimate_FOR_Beginners/upload/
###

###
#config pagination
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true

###
#